/* automatically generated by rust-bindgen 0.71.1 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 40;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
pub const CLAY__ELEMENT_DEFINITION_LATCH: ::std::os::raw::c_int = 0;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_String {
    pub length: ::std::os::raw::c_int,
    pub chars: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_String"][::std::mem::size_of::<Clay_String>() - 16usize];
    ["Alignment of Clay_String"][::std::mem::align_of::<Clay_String>() - 8usize];
    ["Offset of field: Clay_String::length"][::std::mem::offset_of!(Clay_String, length) - 0usize];
    ["Offset of field: Clay_String::chars"][::std::mem::offset_of!(Clay_String, chars) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__StringArray {
    pub capacity: u32,
    pub length: u32,
    pub internalArray: *mut Clay_String,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay__StringArray"][::std::mem::size_of::<Clay__StringArray>() - 16usize];
    ["Alignment of Clay__StringArray"][::std::mem::align_of::<Clay__StringArray>() - 8usize];
    ["Offset of field: Clay__StringArray::capacity"]
        [::std::mem::offset_of!(Clay__StringArray, capacity) - 0usize];
    ["Offset of field: Clay__StringArray::length"]
        [::std::mem::offset_of!(Clay__StringArray, length) - 4usize];
    ["Offset of field: Clay__StringArray::internalArray"]
        [::std::mem::offset_of!(Clay__StringArray, internalArray) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Arena {
    pub label: Clay_String,
    pub nextAllocation: u64,
    pub capacity: u64,
    pub memory: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Arena"][::std::mem::size_of::<Clay_Arena>() - 40usize];
    ["Alignment of Clay_Arena"][::std::mem::align_of::<Clay_Arena>() - 8usize];
    ["Offset of field: Clay_Arena::label"][::std::mem::offset_of!(Clay_Arena, label) - 0usize];
    ["Offset of field: Clay_Arena::nextAllocation"]
        [::std::mem::offset_of!(Clay_Arena, nextAllocation) - 16usize];
    ["Offset of field: Clay_Arena::capacity"]
        [::std::mem::offset_of!(Clay_Arena, capacity) - 24usize];
    ["Offset of field: Clay_Arena::memory"][::std::mem::offset_of!(Clay_Arena, memory) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Dimensions {
    pub width: f32,
    pub height: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Dimensions"][::std::mem::size_of::<Clay_Dimensions>() - 8usize];
    ["Alignment of Clay_Dimensions"][::std::mem::align_of::<Clay_Dimensions>() - 4usize];
    ["Offset of field: Clay_Dimensions::width"]
        [::std::mem::offset_of!(Clay_Dimensions, width) - 0usize];
    ["Offset of field: Clay_Dimensions::height"]
        [::std::mem::offset_of!(Clay_Dimensions, height) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Vector2 {
    pub x: f32,
    pub y: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Vector2"][::std::mem::size_of::<Clay_Vector2>() - 8usize];
    ["Alignment of Clay_Vector2"][::std::mem::align_of::<Clay_Vector2>() - 4usize];
    ["Offset of field: Clay_Vector2::x"][::std::mem::offset_of!(Clay_Vector2, x) - 0usize];
    ["Offset of field: Clay_Vector2::y"][::std::mem::offset_of!(Clay_Vector2, y) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Color {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Color"][::std::mem::size_of::<Clay_Color>() - 16usize];
    ["Alignment of Clay_Color"][::std::mem::align_of::<Clay_Color>() - 4usize];
    ["Offset of field: Clay_Color::r"][::std::mem::offset_of!(Clay_Color, r) - 0usize];
    ["Offset of field: Clay_Color::g"][::std::mem::offset_of!(Clay_Color, g) - 4usize];
    ["Offset of field: Clay_Color::b"][::std::mem::offset_of!(Clay_Color, b) - 8usize];
    ["Offset of field: Clay_Color::a"][::std::mem::offset_of!(Clay_Color, a) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_BoundingBox {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_BoundingBox"][::std::mem::size_of::<Clay_BoundingBox>() - 16usize];
    ["Alignment of Clay_BoundingBox"][::std::mem::align_of::<Clay_BoundingBox>() - 4usize];
    ["Offset of field: Clay_BoundingBox::x"][::std::mem::offset_of!(Clay_BoundingBox, x) - 0usize];
    ["Offset of field: Clay_BoundingBox::y"][::std::mem::offset_of!(Clay_BoundingBox, y) - 4usize];
    ["Offset of field: Clay_BoundingBox::width"]
        [::std::mem::offset_of!(Clay_BoundingBox, width) - 8usize];
    ["Offset of field: Clay_BoundingBox::height"]
        [::std::mem::offset_of!(Clay_BoundingBox, height) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ElementId {
    pub id: u32,
    pub offset: u32,
    pub baseId: u32,
    pub stringId: Clay_String,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ElementId"][::std::mem::size_of::<Clay_ElementId>() - 32usize];
    ["Alignment of Clay_ElementId"][::std::mem::align_of::<Clay_ElementId>() - 8usize];
    ["Offset of field: Clay_ElementId::id"][::std::mem::offset_of!(Clay_ElementId, id) - 0usize];
    ["Offset of field: Clay_ElementId::offset"]
        [::std::mem::offset_of!(Clay_ElementId, offset) - 4usize];
    ["Offset of field: Clay_ElementId::baseId"]
        [::std::mem::offset_of!(Clay_ElementId, baseId) - 8usize];
    ["Offset of field: Clay_ElementId::stringId"]
        [::std::mem::offset_of!(Clay_ElementId, stringId) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_CornerRadius {
    pub topLeft: f32,
    pub topRight: f32,
    pub bottomLeft: f32,
    pub bottomRight: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_CornerRadius"][::std::mem::size_of::<Clay_CornerRadius>() - 16usize];
    ["Alignment of Clay_CornerRadius"][::std::mem::align_of::<Clay_CornerRadius>() - 4usize];
    ["Offset of field: Clay_CornerRadius::topLeft"]
        [::std::mem::offset_of!(Clay_CornerRadius, topLeft) - 0usize];
    ["Offset of field: Clay_CornerRadius::topRight"]
        [::std::mem::offset_of!(Clay_CornerRadius, topRight) - 4usize];
    ["Offset of field: Clay_CornerRadius::bottomLeft"]
        [::std::mem::offset_of!(Clay_CornerRadius, bottomLeft) - 8usize];
    ["Offset of field: Clay_CornerRadius::bottomRight"]
        [::std::mem::offset_of!(Clay_CornerRadius, bottomRight) - 12usize];
};
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_RECTANGLE: Clay__ElementConfigType = 1;
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_BORDER_CONTAINER:
    Clay__ElementConfigType = 2;
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_FLOATING_CONTAINER:
    Clay__ElementConfigType = 4;
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_SCROLL_CONTAINER:
    Clay__ElementConfigType = 8;
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_IMAGE: Clay__ElementConfigType = 16;
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_TEXT: Clay__ElementConfigType = 32;
pub const Clay__ElementConfigType_CLAY__ELEMENT_CONFIG_TYPE_CUSTOM: Clay__ElementConfigType = 64;
pub type Clay__ElementConfigType = ::std::os::raw::c_uchar;
pub const Clay_LayoutDirection_CLAY_LEFT_TO_RIGHT: Clay_LayoutDirection = 0;
pub const Clay_LayoutDirection_CLAY_TOP_TO_BOTTOM: Clay_LayoutDirection = 1;
pub type Clay_LayoutDirection = ::std::os::raw::c_uchar;
pub const Clay_LayoutAlignmentX_CLAY_ALIGN_X_LEFT: Clay_LayoutAlignmentX = 0;
pub const Clay_LayoutAlignmentX_CLAY_ALIGN_X_RIGHT: Clay_LayoutAlignmentX = 1;
pub const Clay_LayoutAlignmentX_CLAY_ALIGN_X_CENTER: Clay_LayoutAlignmentX = 2;
pub type Clay_LayoutAlignmentX = ::std::os::raw::c_uchar;
pub const Clay_LayoutAlignmentY_CLAY_ALIGN_Y_TOP: Clay_LayoutAlignmentY = 0;
pub const Clay_LayoutAlignmentY_CLAY_ALIGN_Y_BOTTOM: Clay_LayoutAlignmentY = 1;
pub const Clay_LayoutAlignmentY_CLAY_ALIGN_Y_CENTER: Clay_LayoutAlignmentY = 2;
pub type Clay_LayoutAlignmentY = ::std::os::raw::c_uchar;
pub const Clay__SizingType_CLAY__SIZING_TYPE_FIT: Clay__SizingType = 0;
pub const Clay__SizingType_CLAY__SIZING_TYPE_GROW: Clay__SizingType = 1;
pub const Clay__SizingType_CLAY__SIZING_TYPE_PERCENT: Clay__SizingType = 2;
pub const Clay__SizingType_CLAY__SIZING_TYPE_FIXED: Clay__SizingType = 3;
pub type Clay__SizingType = ::std::os::raw::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ChildAlignment {
    pub x: Clay_LayoutAlignmentX,
    pub y: Clay_LayoutAlignmentY,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ChildAlignment"][::std::mem::size_of::<Clay_ChildAlignment>() - 2usize];
    ["Alignment of Clay_ChildAlignment"][::std::mem::align_of::<Clay_ChildAlignment>() - 1usize];
    ["Offset of field: Clay_ChildAlignment::x"]
        [::std::mem::offset_of!(Clay_ChildAlignment, x) - 0usize];
    ["Offset of field: Clay_ChildAlignment::y"]
        [::std::mem::offset_of!(Clay_ChildAlignment, y) - 1usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_SizingMinMax {
    pub min: f32,
    pub max: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_SizingMinMax"][::std::mem::size_of::<Clay_SizingMinMax>() - 8usize];
    ["Alignment of Clay_SizingMinMax"][::std::mem::align_of::<Clay_SizingMinMax>() - 4usize];
    ["Offset of field: Clay_SizingMinMax::min"]
        [::std::mem::offset_of!(Clay_SizingMinMax, min) - 0usize];
    ["Offset of field: Clay_SizingMinMax::max"]
        [::std::mem::offset_of!(Clay_SizingMinMax, max) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_SizingAxis {
    pub __bindgen_anon_1: Clay_SizingAxis__bindgen_ty_1,
    pub type_: Clay__SizingType,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union Clay_SizingAxis__bindgen_ty_1 {
    pub sizeMinMax: Clay_SizingMinMax,
    pub sizePercent: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_SizingAxis__bindgen_ty_1"]
        [::std::mem::size_of::<Clay_SizingAxis__bindgen_ty_1>() - 8usize];
    ["Alignment of Clay_SizingAxis__bindgen_ty_1"]
        [::std::mem::align_of::<Clay_SizingAxis__bindgen_ty_1>() - 4usize];
    ["Offset of field: Clay_SizingAxis__bindgen_ty_1::sizeMinMax"]
        [::std::mem::offset_of!(Clay_SizingAxis__bindgen_ty_1, sizeMinMax) - 0usize];
    ["Offset of field: Clay_SizingAxis__bindgen_ty_1::sizePercent"]
        [::std::mem::offset_of!(Clay_SizingAxis__bindgen_ty_1, sizePercent) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_SizingAxis"][::std::mem::size_of::<Clay_SizingAxis>() - 12usize];
    ["Alignment of Clay_SizingAxis"][::std::mem::align_of::<Clay_SizingAxis>() - 4usize];
    ["Offset of field: Clay_SizingAxis::type_"]
        [::std::mem::offset_of!(Clay_SizingAxis, type_) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_Sizing {
    pub width: Clay_SizingAxis,
    pub height: Clay_SizingAxis,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Sizing"][::std::mem::size_of::<Clay_Sizing>() - 24usize];
    ["Alignment of Clay_Sizing"][::std::mem::align_of::<Clay_Sizing>() - 4usize];
    ["Offset of field: Clay_Sizing::width"][::std::mem::offset_of!(Clay_Sizing, width) - 0usize];
    ["Offset of field: Clay_Sizing::height"][::std::mem::offset_of!(Clay_Sizing, height) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Padding {
    pub x: u16,
    pub y: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Padding"][::std::mem::size_of::<Clay_Padding>() - 4usize];
    ["Alignment of Clay_Padding"][::std::mem::align_of::<Clay_Padding>() - 2usize];
    ["Offset of field: Clay_Padding::x"][::std::mem::offset_of!(Clay_Padding, x) - 0usize];
    ["Offset of field: Clay_Padding::y"][::std::mem::offset_of!(Clay_Padding, y) - 2usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_LayoutConfig {
    pub sizing: Clay_Sizing,
    pub padding: Clay_Padding,
    pub childGap: u16,
    pub childAlignment: Clay_ChildAlignment,
    pub layoutDirection: Clay_LayoutDirection,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_LayoutConfig"][::std::mem::size_of::<Clay_LayoutConfig>() - 36usize];
    ["Alignment of Clay_LayoutConfig"][::std::mem::align_of::<Clay_LayoutConfig>() - 4usize];
    ["Offset of field: Clay_LayoutConfig::sizing"]
        [::std::mem::offset_of!(Clay_LayoutConfig, sizing) - 0usize];
    ["Offset of field: Clay_LayoutConfig::padding"]
        [::std::mem::offset_of!(Clay_LayoutConfig, padding) - 24usize];
    ["Offset of field: Clay_LayoutConfig::childGap"]
        [::std::mem::offset_of!(Clay_LayoutConfig, childGap) - 28usize];
    ["Offset of field: Clay_LayoutConfig::childAlignment"]
        [::std::mem::offset_of!(Clay_LayoutConfig, childAlignment) - 30usize];
    ["Offset of field: Clay_LayoutConfig::layoutDirection"]
        [::std::mem::offset_of!(Clay_LayoutConfig, layoutDirection) - 32usize];
};
unsafe extern "C" {
    pub static mut CLAY_LAYOUT_DEFAULT: Clay_LayoutConfig;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_RectangleElementConfig {
    pub color: Clay_Color,
    pub cornerRadius: Clay_CornerRadius,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_RectangleElementConfig"]
        [::std::mem::size_of::<Clay_RectangleElementConfig>() - 32usize];
    ["Alignment of Clay_RectangleElementConfig"]
        [::std::mem::align_of::<Clay_RectangleElementConfig>() - 4usize];
    ["Offset of field: Clay_RectangleElementConfig::color"]
        [::std::mem::offset_of!(Clay_RectangleElementConfig, color) - 0usize];
    ["Offset of field: Clay_RectangleElementConfig::cornerRadius"]
        [::std::mem::offset_of!(Clay_RectangleElementConfig, cornerRadius) - 16usize];
};
pub const Clay_TextElementConfigWrapMode_CLAY_TEXT_WRAP_WORDS: Clay_TextElementConfigWrapMode = 0;
pub const Clay_TextElementConfigWrapMode_CLAY_TEXT_WRAP_NEWLINES: Clay_TextElementConfigWrapMode =
    1;
pub const Clay_TextElementConfigWrapMode_CLAY_TEXT_WRAP_NONE: Clay_TextElementConfigWrapMode = 2;
pub type Clay_TextElementConfigWrapMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TextElementConfig {
    pub textColor: Clay_Color,
    pub fontId: u16,
    pub fontSize: u16,
    pub letterSpacing: u16,
    pub lineHeight: u16,
    pub wrapMode: Clay_TextElementConfigWrapMode,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_TextElementConfig"][::std::mem::size_of::<Clay_TextElementConfig>() - 28usize];
    ["Alignment of Clay_TextElementConfig"]
        [::std::mem::align_of::<Clay_TextElementConfig>() - 4usize];
    ["Offset of field: Clay_TextElementConfig::textColor"]
        [::std::mem::offset_of!(Clay_TextElementConfig, textColor) - 0usize];
    ["Offset of field: Clay_TextElementConfig::fontId"]
        [::std::mem::offset_of!(Clay_TextElementConfig, fontId) - 16usize];
    ["Offset of field: Clay_TextElementConfig::fontSize"]
        [::std::mem::offset_of!(Clay_TextElementConfig, fontSize) - 18usize];
    ["Offset of field: Clay_TextElementConfig::letterSpacing"]
        [::std::mem::offset_of!(Clay_TextElementConfig, letterSpacing) - 20usize];
    ["Offset of field: Clay_TextElementConfig::lineHeight"]
        [::std::mem::offset_of!(Clay_TextElementConfig, lineHeight) - 22usize];
    ["Offset of field: Clay_TextElementConfig::wrapMode"]
        [::std::mem::offset_of!(Clay_TextElementConfig, wrapMode) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ImageElementConfig {
    pub imageData: *mut ::std::os::raw::c_void,
    pub sourceDimensions: Clay_Dimensions,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ImageElementConfig"][::std::mem::size_of::<Clay_ImageElementConfig>() - 16usize];
    ["Alignment of Clay_ImageElementConfig"]
        [::std::mem::align_of::<Clay_ImageElementConfig>() - 8usize];
    ["Offset of field: Clay_ImageElementConfig::imageData"]
        [::std::mem::offset_of!(Clay_ImageElementConfig, imageData) - 0usize];
    ["Offset of field: Clay_ImageElementConfig::sourceDimensions"]
        [::std::mem::offset_of!(Clay_ImageElementConfig, sourceDimensions) - 8usize];
};
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_LEFT_TOP: Clay_FloatingAttachPointType = 0;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_LEFT_CENTER: Clay_FloatingAttachPointType =
    1;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_LEFT_BOTTOM: Clay_FloatingAttachPointType =
    2;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_CENTER_TOP: Clay_FloatingAttachPointType =
    3;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_CENTER_CENTER:
    Clay_FloatingAttachPointType = 4;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_CENTER_BOTTOM:
    Clay_FloatingAttachPointType = 5;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_RIGHT_TOP: Clay_FloatingAttachPointType =
    6;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_RIGHT_CENTER:
    Clay_FloatingAttachPointType = 7;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_RIGHT_BOTTOM:
    Clay_FloatingAttachPointType = 8;
pub type Clay_FloatingAttachPointType = ::std::os::raw::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_FloatingAttachPoints {
    pub element: Clay_FloatingAttachPointType,
    pub parent: Clay_FloatingAttachPointType,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_FloatingAttachPoints"]
        [::std::mem::size_of::<Clay_FloatingAttachPoints>() - 2usize];
    ["Alignment of Clay_FloatingAttachPoints"]
        [::std::mem::align_of::<Clay_FloatingAttachPoints>() - 1usize];
    ["Offset of field: Clay_FloatingAttachPoints::element"]
        [::std::mem::offset_of!(Clay_FloatingAttachPoints, element) - 0usize];
    ["Offset of field: Clay_FloatingAttachPoints::parent"]
        [::std::mem::offset_of!(Clay_FloatingAttachPoints, parent) - 1usize];
};
pub const Clay_PointerCaptureMode_CLAY_POINTER_CAPTURE_MODE_CAPTURE: Clay_PointerCaptureMode = 0;
pub const Clay_PointerCaptureMode_CLAY_POINTER_CAPTURE_MODE_PASSTHROUGH: Clay_PointerCaptureMode =
    1;
pub type Clay_PointerCaptureMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_FloatingElementConfig {
    pub offset: Clay_Vector2,
    pub expand: Clay_Dimensions,
    pub zIndex: u16,
    pub parentId: u32,
    pub attachment: Clay_FloatingAttachPoints,
    pub pointerCaptureMode: Clay_PointerCaptureMode,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_FloatingElementConfig"]
        [::std::mem::size_of::<Clay_FloatingElementConfig>() - 32usize];
    ["Alignment of Clay_FloatingElementConfig"]
        [::std::mem::align_of::<Clay_FloatingElementConfig>() - 4usize];
    ["Offset of field: Clay_FloatingElementConfig::offset"]
        [::std::mem::offset_of!(Clay_FloatingElementConfig, offset) - 0usize];
    ["Offset of field: Clay_FloatingElementConfig::expand"]
        [::std::mem::offset_of!(Clay_FloatingElementConfig, expand) - 8usize];
    ["Offset of field: Clay_FloatingElementConfig::zIndex"]
        [::std::mem::offset_of!(Clay_FloatingElementConfig, zIndex) - 16usize];
    ["Offset of field: Clay_FloatingElementConfig::parentId"]
        [::std::mem::offset_of!(Clay_FloatingElementConfig, parentId) - 20usize];
    ["Offset of field: Clay_FloatingElementConfig::attachment"]
        [::std::mem::offset_of!(Clay_FloatingElementConfig, attachment) - 24usize];
    ["Offset of field: Clay_FloatingElementConfig::pointerCaptureMode"]
        [::std::mem::offset_of!(Clay_FloatingElementConfig, pointerCaptureMode) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_CustomElementConfig {
    pub customData: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_CustomElementConfig"]
        [::std::mem::size_of::<Clay_CustomElementConfig>() - 8usize];
    ["Alignment of Clay_CustomElementConfig"]
        [::std::mem::align_of::<Clay_CustomElementConfig>() - 8usize];
    ["Offset of field: Clay_CustomElementConfig::customData"]
        [::std::mem::offset_of!(Clay_CustomElementConfig, customData) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ScrollElementConfig {
    pub horizontal: bool,
    pub vertical: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ScrollElementConfig"]
        [::std::mem::size_of::<Clay_ScrollElementConfig>() - 2usize];
    ["Alignment of Clay_ScrollElementConfig"]
        [::std::mem::align_of::<Clay_ScrollElementConfig>() - 1usize];
    ["Offset of field: Clay_ScrollElementConfig::horizontal"]
        [::std::mem::offset_of!(Clay_ScrollElementConfig, horizontal) - 0usize];
    ["Offset of field: Clay_ScrollElementConfig::vertical"]
        [::std::mem::offset_of!(Clay_ScrollElementConfig, vertical) - 1usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Border {
    pub width: u32,
    pub color: Clay_Color,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_Border"][::std::mem::size_of::<Clay_Border>() - 20usize];
    ["Alignment of Clay_Border"][::std::mem::align_of::<Clay_Border>() - 4usize];
    ["Offset of field: Clay_Border::width"][::std::mem::offset_of!(Clay_Border, width) - 0usize];
    ["Offset of field: Clay_Border::color"][::std::mem::offset_of!(Clay_Border, color) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_BorderElementConfig {
    pub left: Clay_Border,
    pub right: Clay_Border,
    pub top: Clay_Border,
    pub bottom: Clay_Border,
    pub betweenChildren: Clay_Border,
    pub cornerRadius: Clay_CornerRadius,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_BorderElementConfig"]
        [::std::mem::size_of::<Clay_BorderElementConfig>() - 116usize];
    ["Alignment of Clay_BorderElementConfig"]
        [::std::mem::align_of::<Clay_BorderElementConfig>() - 4usize];
    ["Offset of field: Clay_BorderElementConfig::left"]
        [::std::mem::offset_of!(Clay_BorderElementConfig, left) - 0usize];
    ["Offset of field: Clay_BorderElementConfig::right"]
        [::std::mem::offset_of!(Clay_BorderElementConfig, right) - 20usize];
    ["Offset of field: Clay_BorderElementConfig::top"]
        [::std::mem::offset_of!(Clay_BorderElementConfig, top) - 40usize];
    ["Offset of field: Clay_BorderElementConfig::bottom"]
        [::std::mem::offset_of!(Clay_BorderElementConfig, bottom) - 60usize];
    ["Offset of field: Clay_BorderElementConfig::betweenChildren"]
        [::std::mem::offset_of!(Clay_BorderElementConfig, betweenChildren) - 80usize];
    ["Offset of field: Clay_BorderElementConfig::cornerRadius"]
        [::std::mem::offset_of!(Clay_BorderElementConfig, cornerRadius) - 100usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union Clay_ElementConfigUnion {
    pub rectangleElementConfig: *mut Clay_RectangleElementConfig,
    pub textElementConfig: *mut Clay_TextElementConfig,
    pub imageElementConfig: *mut Clay_ImageElementConfig,
    pub floatingElementConfig: *mut Clay_FloatingElementConfig,
    pub customElementConfig: *mut Clay_CustomElementConfig,
    pub scrollElementConfig: *mut Clay_ScrollElementConfig,
    pub borderElementConfig: *mut Clay_BorderElementConfig,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ElementConfigUnion"][::std::mem::size_of::<Clay_ElementConfigUnion>() - 8usize];
    ["Alignment of Clay_ElementConfigUnion"]
        [::std::mem::align_of::<Clay_ElementConfigUnion>() - 8usize];
    ["Offset of field: Clay_ElementConfigUnion::rectangleElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, rectangleElementConfig) - 0usize];
    ["Offset of field: Clay_ElementConfigUnion::textElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, textElementConfig) - 0usize];
    ["Offset of field: Clay_ElementConfigUnion::imageElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, imageElementConfig) - 0usize];
    ["Offset of field: Clay_ElementConfigUnion::floatingElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, floatingElementConfig) - 0usize];
    ["Offset of field: Clay_ElementConfigUnion::customElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, customElementConfig) - 0usize];
    ["Offset of field: Clay_ElementConfigUnion::scrollElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, scrollElementConfig) - 0usize];
    ["Offset of field: Clay_ElementConfigUnion::borderElementConfig"]
        [::std::mem::offset_of!(Clay_ElementConfigUnion, borderElementConfig) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_ElementConfig {
    pub type_: Clay__ElementConfigType,
    pub config: Clay_ElementConfigUnion,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ElementConfig"][::std::mem::size_of::<Clay_ElementConfig>() - 16usize];
    ["Alignment of Clay_ElementConfig"][::std::mem::align_of::<Clay_ElementConfig>() - 8usize];
    ["Offset of field: Clay_ElementConfig::type_"]
        [::std::mem::offset_of!(Clay_ElementConfig, type_) - 0usize];
    ["Offset of field: Clay_ElementConfig::config"]
        [::std::mem::offset_of!(Clay_ElementConfig, config) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ScrollContainerData {
    pub scrollPosition: *mut Clay_Vector2,
    pub scrollContainerDimensions: Clay_Dimensions,
    pub contentDimensions: Clay_Dimensions,
    pub config: Clay_ScrollElementConfig,
    pub found: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_ScrollContainerData"]
        [::std::mem::size_of::<Clay_ScrollContainerData>() - 32usize];
    ["Alignment of Clay_ScrollContainerData"]
        [::std::mem::align_of::<Clay_ScrollContainerData>() - 8usize];
    ["Offset of field: Clay_ScrollContainerData::scrollPosition"]
        [::std::mem::offset_of!(Clay_ScrollContainerData, scrollPosition) - 0usize];
    ["Offset of field: Clay_ScrollContainerData::scrollContainerDimensions"]
        [::std::mem::offset_of!(Clay_ScrollContainerData, scrollContainerDimensions) - 8usize];
    ["Offset of field: Clay_ScrollContainerData::contentDimensions"]
        [::std::mem::offset_of!(Clay_ScrollContainerData, contentDimensions) - 16usize];
    ["Offset of field: Clay_ScrollContainerData::config"]
        [::std::mem::offset_of!(Clay_ScrollContainerData, config) - 24usize];
    ["Offset of field: Clay_ScrollContainerData::found"]
        [::std::mem::offset_of!(Clay_ScrollContainerData, found) - 26usize];
};
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_NONE: Clay_RenderCommandType = 0;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_RECTANGLE: Clay_RenderCommandType = 1;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_BORDER: Clay_RenderCommandType = 2;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_TEXT: Clay_RenderCommandType = 3;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_IMAGE: Clay_RenderCommandType = 4;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_SCISSOR_START: Clay_RenderCommandType = 5;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_SCISSOR_END: Clay_RenderCommandType = 6;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_CUSTOM: Clay_RenderCommandType = 7;
pub type Clay_RenderCommandType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_RenderCommand {
    pub boundingBox: Clay_BoundingBox,
    pub config: Clay_ElementConfigUnion,
    pub text: Clay_String,
    pub id: u32,
    pub commandType: Clay_RenderCommandType,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_RenderCommand"][::std::mem::size_of::<Clay_RenderCommand>() - 48usize];
    ["Alignment of Clay_RenderCommand"][::std::mem::align_of::<Clay_RenderCommand>() - 8usize];
    ["Offset of field: Clay_RenderCommand::boundingBox"]
        [::std::mem::offset_of!(Clay_RenderCommand, boundingBox) - 0usize];
    ["Offset of field: Clay_RenderCommand::config"]
        [::std::mem::offset_of!(Clay_RenderCommand, config) - 16usize];
    ["Offset of field: Clay_RenderCommand::text"]
        [::std::mem::offset_of!(Clay_RenderCommand, text) - 24usize];
    ["Offset of field: Clay_RenderCommand::id"]
        [::std::mem::offset_of!(Clay_RenderCommand, id) - 40usize];
    ["Offset of field: Clay_RenderCommand::commandType"]
        [::std::mem::offset_of!(Clay_RenderCommand, commandType) - 44usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_RenderCommandArray {
    pub capacity: u32,
    pub length: u32,
    pub internalArray: *mut Clay_RenderCommand,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_RenderCommandArray"][::std::mem::size_of::<Clay_RenderCommandArray>() - 16usize];
    ["Alignment of Clay_RenderCommandArray"]
        [::std::mem::align_of::<Clay_RenderCommandArray>() - 8usize];
    ["Offset of field: Clay_RenderCommandArray::capacity"]
        [::std::mem::offset_of!(Clay_RenderCommandArray, capacity) - 0usize];
    ["Offset of field: Clay_RenderCommandArray::length"]
        [::std::mem::offset_of!(Clay_RenderCommandArray, length) - 4usize];
    ["Offset of field: Clay_RenderCommandArray::internalArray"]
        [::std::mem::offset_of!(Clay_RenderCommandArray, internalArray) - 8usize];
};
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_PRESSED_THIS_FRAME:
    Clay_PointerDataInteractionState = 0;
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_PRESSED:
    Clay_PointerDataInteractionState = 1;
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_RELEASED_THIS_FRAME:
    Clay_PointerDataInteractionState = 2;
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_RELEASED:
    Clay_PointerDataInteractionState = 3;
pub type Clay_PointerDataInteractionState = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_PointerData {
    pub position: Clay_Vector2,
    pub state: Clay_PointerDataInteractionState,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Clay_PointerData"][::std::mem::size_of::<Clay_PointerData>() - 12usize];
    ["Alignment of Clay_PointerData"][::std::mem::align_of::<Clay_PointerData>() - 4usize];
    ["Offset of field: Clay_PointerData::position"]
        [::std::mem::offset_of!(Clay_PointerData, position) - 0usize];
    ["Offset of field: Clay_PointerData::state"]
        [::std::mem::offset_of!(Clay_PointerData, state) - 8usize];
};
unsafe extern "C" {
    pub fn Clay_MinMemorySize() -> u32;
}
unsafe extern "C" {
    pub fn Clay_CreateArenaWithCapacityAndMemory(
        capacity: u32,
        offset: *mut ::std::os::raw::c_void,
    ) -> Clay_Arena;
}
unsafe extern "C" {
    pub fn Clay_SetPointerState(position: Clay_Vector2, pointerDown: bool);
}
unsafe extern "C" {
    pub fn Clay_Initialize(arena: Clay_Arena, layoutDimensions: Clay_Dimensions);
}
unsafe extern "C" {
    pub fn Clay_UpdateScrollContainers(
        enableDragScrolling: bool,
        scrollDelta: Clay_Vector2,
        deltaTime: f32,
    );
}
unsafe extern "C" {
    pub fn Clay_SetLayoutDimensions(dimensions: Clay_Dimensions);
}
unsafe extern "C" {
    pub fn Clay_BeginLayout();
}
unsafe extern "C" {
    pub fn Clay_EndLayout() -> Clay_RenderCommandArray;
}
unsafe extern "C" {
    pub fn Clay_GetElementId(idString: Clay_String) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay_GetElementIdWithIndex(idString: Clay_String, index: u32) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay_Hovered() -> bool;
}
unsafe extern "C" {
    pub fn Clay_OnHover(
        onHoverFunction: ::std::option::Option<
            unsafe extern "C" fn(
                elementId: Clay_ElementId,
                pointerData: Clay_PointerData,
                userData: isize,
            ),
        >,
        userData: isize,
    );
}
unsafe extern "C" {
    pub fn Clay_GetScrollContainerData(id: Clay_ElementId) -> Clay_ScrollContainerData;
}
unsafe extern "C" {
    pub fn Clay_SetMeasureTextFunction(
        measureTextFunction: ::std::option::Option<
            unsafe extern "C" fn(
                text: *mut Clay_String,
                config: *mut Clay_TextElementConfig,
            ) -> Clay_Dimensions,
        >,
    );
}
unsafe extern "C" {
    pub fn Clay_SetQueryScrollOffsetFunction(
        queryScrollOffsetFunction: ::std::option::Option<
            unsafe extern "C" fn(elementId: u32) -> Clay_Vector2,
        >,
    );
}
unsafe extern "C" {
    pub fn Clay_RenderCommandArray_Get(
        array: *mut Clay_RenderCommandArray,
        index: i32,
    ) -> *mut Clay_RenderCommand;
}
unsafe extern "C" {
    pub fn Clay_SetDebugModeEnabled(enabled: bool);
}
unsafe extern "C" {
    pub fn Clay_SetCullingEnabled(enabled: bool);
}
unsafe extern "C" {
    pub fn Clay__OpenElement();
}
unsafe extern "C" {
    pub fn Clay__CloseElement();
}
unsafe extern "C" {
    pub fn Clay__StoreLayoutConfig(config: Clay_LayoutConfig) -> *mut Clay_LayoutConfig;
}
unsafe extern "C" {
    pub fn Clay__ElementPostConfiguration();
}
unsafe extern "C" {
    pub fn Clay__AttachId(id: Clay_ElementId);
}
unsafe extern "C" {
    pub fn Clay__AttachLayoutConfig(config: *mut Clay_LayoutConfig);
}
unsafe extern "C" {
    pub fn Clay__AttachElementConfig(
        config: Clay_ElementConfigUnion,
        type_: Clay__ElementConfigType,
    );
}
unsafe extern "C" {
    pub fn Clay__StoreRectangleElementConfig(
        config: Clay_RectangleElementConfig,
    ) -> *mut Clay_RectangleElementConfig;
}
unsafe extern "C" {
    pub fn Clay__StoreTextElementConfig(
        config: Clay_TextElementConfig,
    ) -> *mut Clay_TextElementConfig;
}
unsafe extern "C" {
    pub fn Clay__StoreImageElementConfig(
        config: Clay_ImageElementConfig,
    ) -> *mut Clay_ImageElementConfig;
}
unsafe extern "C" {
    pub fn Clay__StoreFloatingElementConfig(
        config: Clay_FloatingElementConfig,
    ) -> *mut Clay_FloatingElementConfig;
}
unsafe extern "C" {
    pub fn Clay__StoreCustomElementConfig(
        config: Clay_CustomElementConfig,
    ) -> *mut Clay_CustomElementConfig;
}
unsafe extern "C" {
    pub fn Clay__StoreScrollElementConfig(
        config: Clay_ScrollElementConfig,
    ) -> *mut Clay_ScrollElementConfig;
}
unsafe extern "C" {
    pub fn Clay__StoreBorderElementConfig(
        config: Clay_BorderElementConfig,
    ) -> *mut Clay_BorderElementConfig;
}
unsafe extern "C" {
    pub fn Clay__HashString(key: Clay_String, offset: u32, seed: u32) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay__Noop();
}
unsafe extern "C" {
    pub fn Clay__OpenTextElement(text: Clay_String, textConfig: *mut Clay_TextElementConfig);
}
unsafe extern "C" {
    pub static mut Clay__debugViewHighlightColor: Clay_Color;
}
unsafe extern "C" {
    pub static mut Clay__debugViewWidth: u32;
}
unsafe extern "C" {
    pub static mut Clay__debugMaxElementsLatch: bool;
}
